# Generated by Django 4.2 on 2024-08-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userrole_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userrole",
            options={"verbose_name": "user role", "verbose_name_plural": "user roles"},
        ),
    ]
