# Generated by Django 5.0.7 on 2024-08-03 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("airlines", "0001_initial"),
        ("airports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.CharField(max_length=20, unique=True)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                ("duration", models.DurationField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("seats_available", models.PositiveIntegerField(default=60)),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airlines.airline",
                    ),
                ),
                (
                    "arrival_airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrivals",
                        to="airports.airport",
                    ),
                ),
                (
                    "departure_airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departures",
                        to="airports.airport",
                    ),
                ),
            ],
            options={
                "verbose_name": "flight",
                "verbose_name_plural": "flights",
                "ordering": ["departure_time"],
            },
        ),
        migrations.CreateModel(
            name="FlightSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule_date", models.DateField()),
                ("departure_time", models.TimeField()),
                ("arrival_time", models.TimeField()),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_schedule",
                        to="flights.flight",
                    ),
                ),
            ],
            options={
                "verbose_name": "flight schedule",
                "verbose_name_plural": "flight schedules",
            },
        ),
    ]
