# Generated by Django 5.0.7 on 2024-08-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="airline_logos/"
                    ),
                ),
            ],
            options={
                "verbose_name": "airline",
                "verbose_name_plural": "airlines",
            },
        ),
    ]
